### PR TITLE
Implemented advanced settings

### PR DESCRIPTION
**Pull request by BondarenkoArtur**
I've implemented additional offsets and rotations for images. Solves https://github.com/Nettakrim/Signed-Paintings/issues/24

Here is how it looks like

https://github.com/Nettakrim/Signed-Paintings/assets/9720950/7609271c-cdac-4402-8bb6-0546508acbed

### CODE REVIEW

**Comment by Nettakrim** [comment]
ooh putting it in a sub menu is nice

i wonder if it would make more sense to remove the Y offset slider and rename "Advanced Settings" to "Positioning" or something instead
(then the left and right would also have the same amount of buttons and can be aligned, currently it looks a bit funny)

its good that my funky slider text box is working well

that sign edit screen mixin is getting pretty large, ill probably try refactor it since there is a fair amount of repetition

**Comment by BondarenkoArtur** [comment]
Refactoring is always good :D

**Comment by BondarenkoArtur** [comment]
Was trying to rework some parts of UI, what do you think?
Screenshot_20240613_000755

**Comment by Nettakrim** [comment]
having the sign off to the side is interesting, but i do feel like putting all of the buttons into a big block looks a bit cluttered/overwhelming and that it obstructs the players view of the image

ill mess around in ms paint and see if i can find a good layout

**Comment by Nettakrim** [comment]
in theory you probably dont need to access alignment if youre using the free positioning, so the sub menu could replace it like this
image

but the smaller sign is nice, it could work to try align everything to be a fixed distance from the edge of the screen (instead of from the center), and then keep the entire middle of the screen clear, and reduce clutter by having the offsets be a thing thats toggled between
image

or have everything at once, but shoved to the side (this might be hard to fit, i also dont know how it works with gui scale?)
image

the smaller sign does also look like it roughly lines up with the size of the alignment grid, so something like this might work nicely
image

(the offsets should probably also be above the rotation in those last 2)

**Comment by BondarenkoArtur** [comment]
And transparent background?

**Comment by Nettakrim** [comment]
oh yeah at that point we could remove it if we wanted for visibility, although it is good for contrast, may as well keep it

**Comment by BondarenkoArtur** [comment]
image
image

Changed UI a bit, now overlays are attached to top left/right corners of screen. 
UI still requires better refactoring, but not in this PR.

**Comment by BondarenkoArtur** [comment]
For 1.20.1 Sliders looks a bit incorrect. :( 
Probably mixin to SliderWidget is required to fix it, if we really need it to be perfect in 1.20.1

**Comment by Nettakrim** [comment]
ooh yeah thats good, is the issue with sliders to do with the narrower buttons?

**Comment by Nettakrim** [comment]
ill probably merge that later today after i finish fixing one of my other mods

**Comment by BondarenkoArtur** [comment]
> ooh yeah thats good, is the issue with sliders to do with the narrower buttons?

Yes,  the actual slider is too long on 1.20.1

**Comment by Nettakrim** [comment]
ooh thats fun i can merge from idea

**Comment by Nettakrim** [comment]
huh why are you using a Vec3d when you always cast it into float, why isnt it just a Vector3f?

**Comment by BondarenkoArtur** [comment]
> huh why are you using a Vec3d when you always cast it into float, why isnt it just a Vector3f?

Sorry, probably just dumb mistake. I don't remember any actual reason why I used specifically that one. I guess we can switch to Vector3f. And maybe store offsets in same format.

**Comment by BondarenkoArtur** [comment]
Are you planning new release with this features?

**Comment by Nettakrim** [comment]
yeah, im currently doing some tweaks

**Pull request merged**
